# Pre-define Devices
deviceList:
- name: "deviceB"
  profileName: "deviceB-profile"
  description: "MQTT deviceB"
  labels: [ "MQTT", "test" ]
  protocols:
    mqtt:
      CommandTopic: "command/devices-topic"
  autoEvents:
    - interval: "5s"
      onChange: false
      sourceName: "randnum"