# Pre-define Devices
deviceList:
- name: "my-mqtt-device"
  profileName: "my-mqtt-device-profile"
  description: "MQTT device is created for test purpose"
  labels: [ "MQTT", "test" ]
  protocols:
    mqtt:
      CommandTopic: "command/my-mqtt-device"
  autoEvents:
    - interval: "30s"
      onChange: false
      sourceName: "message"